version: "3.9"

volumes:
  mssqldata: {}

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: medications_service
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/opt/project
    env_file:
      - ./.envs/.django
      - ./.envs/.mssql

  db:
    image: islamusayman95/mssqldocker:latest
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    env_file:
      - ./.envs/.mssql