version: "3.9"
services:
  db:
    build: .
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      SA_PASSWORD: "yourStrong(!)Password"
      DB_NAME: demo