version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: medications_service
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/opt/project
    env_file:
      - ./.env/.dev

  db:
    image: islamusayman95/mssqldocker:latest
    ports:
      - "1433:1433"

    env_file:
      - ./.env/.dev